### ISSUE TITLE
[iOS 13.5.1] Notifications never show up without having session running in foreground

### ISSUE THREAD

**Issue by ghost** [loki-project/session-ios#217] opened 2020-06-18 15:49 UTC
### Patient Info:
Name: Session iOS version 1.2.3
Body type: iPhone X 
Blood group: iOS 13.5.1

### Steps to reproduce
- Open the app
- Enable APNs (use Apple Notification Push Service)
- Open a group chat
- Type whatever then switch out the app to run in the background

**Actual result:** 
Somebody replied me after several minutes(?) but no notification showed up until I opened the app. The monent the app switched back to the foregorund, notifications showed up.

**Expected result:** 
Meh... the patient should make noise when messages arrived.

### Screenshots
404

### Notes
- No crash log available.
- Permissions for notifications, background are granted.
- Turning on and off background polling doesn't help.
- I tested this only in group chat as I don't have any contacts yet.

**Comment by KeeJef** [comment] 2020-06-19 00:46
Push notifications should be received generally no more than 90 seconds after the message is sent, usually before this, did you not receive a notification 90 seconds after your friend messaged you?

**Comment by kolmstori** [comment] 2020-06-19 08:03
> Push notifications should be received generally no more than 90 seconds after the message is sent, usually before this, did you not receive a notification 90 seconds after your friend messaged you?

Hi. I don't have any contact except one group chat (loki community) in my session. So I cannot test the case like one-to-one chat. I am thinking If it's a good idea to post my session id in the group so that I could get some contacts for test purpose.

**Comment by nielsandriesse** [comment] 2020-06-23 05:52
Open groups work through background polling instead of APNs, making push notifications for them much less frequent (for one-to-one sessions and closed groups the max delivery time should be sub 90 seconds but for open groups it's determined by iOS so it could be several hours). This is a known thing that we'll be looking into in the future, but it's not a bug with the current system.

**Comment by Winflem** [comment] 2020-09-07 12:12
Same to me. I´m on an iPhone X with actual OS. I never get any notifications. They come in ONLY if I have the app in FOREGROUND running. I would like to use and test the app but with this behaviour it is useless to me.

**Comment by nielsandriesse** [comment] 2020-12-17 23:23
Closing this as push notifications are working fine in one-on-one conversations and closed groups. Making them faster for open groups is on our roadmap.

**Closed by nielsandriesse** 2020-12-17 23:23 UTC
